### ISSUE TITLE
How am I supposed to apply theme ?

### ISSUE THREAD

**Issue by FBDev64** [notAxon/dotfiles#4]
I copied this in the .config of awesome, but now, how to apply theme ? Only colors are changed, no background, nothing.

**Comment by notAxon** [comment]
[wallpapers](https://github.com/notAxon/wallpapers)

[current dotfiles](https://github.com/notAxon/awesome-dots/tree/main)

if you want to recreate what is shown in the screenshot, copy everything into `~/.config/` except for `/fonts`, which belong in `/usr/share/`.

**Comment by FBDev64** [comment]
Thanks. Not using awesome anymore, but excellent. Gotta reinstall it with everything.
